name: Sync Notion to Github

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  sync-notion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get Notion Data
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: python python_notion_to_md.py

      - name: Check if there are any changes
        id: verify_diff
        run: |
            git diff --exit-code || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Git Commit&Push
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
            git config --global user.name "5a6io"
            git config --global user.email "${{ secrets.EMAIL }}"
            git add .
            git commit -m "Automatic Update: Reflect Notion Data"
            git push -u origin main